# Training parameters
max_epoch: 2

# Model parameters
lpr_max_len: 7
dropout_rate: 0.5
class_num: 37  # len(CHARS)
T_length: 20

# Dataset paths
train_img_dirs: "data/train"
test_img_dirs: "data/test"
num_workers: 8

# Training configuration
train_batch_size: 256
test_batch_size: 128

# Optimizer parameters
learning_rate: 0.001
momentum: 0.95
weight_decay: 0.00005

# LR Scheduler
gamma: 0.9

# Checkpoint and evaluation
save_interval: 100
test_interval: 100
save_folder: "./weights/"
pretrained_model: # "./weights_all/LPRNet__iteration_88000.pth" # "weights/LPRNet__iteration_876000.pth"

# Device
cuda: true

# wandb
entity: "vovanthinhv225-ho-chi-minh-city-university-of-technology"
project: "lprnet"

# Beam Search
topk: 3